### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by m0rth** [antzucaro/xonstatdb#2]
I noticed 2 typos:

In build/build_full.sql you execute a tables/active_maps_mv.tab but the file is named tables/active_maps_mv.sql

In the README.md there is "pgplsql* language" and "CREATE LANGUAGE plpgsql;"

**Comment by antzucaro** [comment]
I will fix them both ASAP. Thank you!

**Comment by antzucaro** [comment]
Fixed with commit 8dc27f4233a61a93152f8b4b1b16de3e713d943e.
